config/routes.rb
Rails.application.routes.draw do

  namespace :dashboard do
  get 'orders/index'
  end

  root 'pages#home'
  get '/features', to: 'pages#features'

  devise_for :users,
             controllers: { registrations: "registrations" }

  namespace :dashboard do
    get '/', to: 'dashboard#index'
    get '/account', to: 'dashboard#account'
    get '/staff', to: 'dashboard#staff'

    resources :products
    resources :purchases
    resources :users
    resources :orders
  end

  resources :products, only: [:index, :show] do
  	resources :purchases
  end
  resources :balances
  resources :sellers, only: [:index, :show]

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :product_image, ProductImageUploader
	
  has_many :purchases, dependent: :destroy

  belongs_to :user
  belongs_to :category
  belongs_to :district

  monetize :price_cents

  geocoded_by :address
  after_validation :geocode  , :if => :address_changed?

end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_action :authenticate_user!
  layout :layout
  
  def index
  end

  def account
  end

  # BPMS staff
  def staff
 	@users = User.where(role: 1).order("created_at DESC")
  end

end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < ApplicationController
  before_action :authenticate_user!
  layout :layout

  def index
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
  layout 'dashboard'

  def index
  	@products = current_user.products.order("created_at DESC")
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
  	@product = Product.new
  end

  def create
  	if current_user.products.create(product_params)
      flash[:success]= "Product created successfully"
  		redirect_to dashboard_products_path
  	end
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Porduct has been removed"
    redirect_to dashboard_path
  end

  private	
  	def product_params
  		params.require(:product).permit(:name, :price_cents, :quantity, :description, :product_image, :user_id, :latitude, :longitude).merge(address: current_user.address)
  	end
end

app/controllers/dashboard/purchases_controller.rb
class Dashboard::PurchasesController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  
  def index
  	@purchases = Purchase.where(buyer: current_user).order("created_at DESC").all
  	@sold = Purchase.where(seller: current_user).order("created_at DESC").all
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  
  def update
  	if User.find(current_user).update_attribute(:profile_image, params[:user][:profile_image])
  		flash[:success] = "Profile updated"
  		redirect_to dashboard_account_path
  	end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout :layout
  
  def index
  end

  def shop
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 12).order("created_at DESC")
  end

  def show
    @product = Product.friendly.find(params[:id])
  end

  private	
  	def product_params
  		params.require(:product).permit(:name, :price_cents, :quantity, :description, :product_image, :shop_id)
  	end
end

app/helpers/dashboard/balances_helper.rb
module Dashboard::BalancesHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/dashboard/purchases_helper.rb
module Dashboard::PurchasesHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/products/index.html.erb
<div class="box">
	<p class="text-center"><%= link_to "New Product", new_dashboard_product_path, class: "btn btn-secondary" %></p>
	<%if current_user.products.present? %>
		<table class="table table-striped"><br>
		    <thead>
		      <tr>
		        <th>Name</th>
		        <th>Image</th>
		        <th>Quantity</th>
		        <th>Price</th>
		        <th>Manage</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<% @products.each do |product| %>
				  <tr>
			        <td><%= product.name %></td>
			        <td><%= image_tag(product.product_image_url(:tiny)) if product.product_image.tiny.present? %></td>
			        <td><%= product.quantity %></td>
			        <td><%= humanized_money_with_symbol(product.price_cents) %></td>
			        <td><%= link_to "Edit", root_path, class: "btn btn-secondary btn-xs" %> <%= link_to "Delete", dashboard_product_path(product), method: :delete, class: "btn btn-danger btn-xs" %></td>
			      </tr>
		    	<% end %>
		    </tbody>
		</table>
	<% end %>
</div>

app/views/dashboard/products/new.html.erb
<div class="col-md-6 center-block box">
	<h3 class="text-center">Add a new product</h3>
	<%= form_for [:dashboard, @product], html: {multipart: true} do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :price_cents, "Price" %>
			<%= f.text_field :price_cents, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :quantity %>
			<%= f.number_field :quantity, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.hidden_field(:product_image_cache) %>
			<%= f.label :product_image, "Select product image" %>
			<%= f.file_field :product_image %>
		</div>
		<%= f.submit "Create Product", class: "form-control btn btn-primary" %>
	<% end %>
</div>

app/views/dashboard/products/show.html.erb
<div class="row">
	<div class="col-md-8 box center-block text-center">
		<h3><%= @product.name %></h3>
		<h4>Seller: <%= link_to @product.shop.name, shop_path(@product.shop) %></h4>
		<%= image_tag(@product.product_image) if @product.product_image? %>
		<h4>Price: <%= humanized_money_with_symbol(@product.price_cents) %></h4>
		<p><%= @product.description %></p>
		<%=link_to "Purchase", new_product_purchase_path(@product), class: "btn btn-secondary" %>
	</div>
</div>

<div class="row">
	<h3 class="text-center">Other products</h3>
	<% Product.where.not(id: @product.id).limit(8).each do |product| %>
		<div class="col-md-3">
			<div class="product-wrapper">
				<%= image_tag(product.product_image.normal) if product.product_image? %>
				<h4 class="text-center"><%= link_to product.name, shop_product_path(product.shop, product) %></h4>
			</div>
		</div>
	<% end %>
</div>