config/routes.rb
Rails.application.routes.draw do

  namespace :dashboard do
  get 'orders/index'
  end

  root 'pages#home'
  get '/features', to: 'pages#features'

  devise_for :users,
             controllers: { registrations: "registrations" }

  namespace :dashboard do
    get '/', to: 'dashboard#index'
    get '/account', to: 'dashboard#account'
    get '/staff', to: 'dashboard#staff'

    resources :products
    resources :purchases
    resources :users
    resources :orders
  end

  resources :products, only: [:index, :show] do
  	resources :purchases
  end
  resources :balances
  resources :sellers, only: [:index, :show]

end

app/models/balance.rb
class Balance < ActiveRecord::Base
  belongs_to :shop
  belongs_to :user

  monetize :amount_cents
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/code.rb
class Code < ActiveRecord::Base
	has_one :purchase

	monetize :value_cents
end

app/models/district.rb
class District < ActiveRecord::Base
	has_many :users
	has_many :products


end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :purchase
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :product_image, ProductImageUploader
	
  has_many :purchases, dependent: :destroy

  belongs_to :user
  belongs_to :category
  belongs_to :district

  monetize :price_cents

  geocoded_by :address
  after_validation :geocode  , :if => :address_changed?

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :code
  belongs_to :product
  
  belongs_to :seller, :class_name => "User"
  belongs_to :buyer, :class_name => "User"

  has_one :order 
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :profile_image, ProfileImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :balance

  has_many :products, dependent: :destroy
  has_many :purchases, dependent: :destroy

  belongs_to :district

  geocoded_by :address
  after_validation :geocode  , :if => :address_changed?

  # user roles structure, default - seller
  enum role: [:normal, :delivery, :admin]
  # sets default role only if its a new record(i.e. object does not exist yet)
  after_initialize :set_default_role, :if => :new_record?

   # set default role for user
  def set_default_role
  	self.role ||= :normal
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  def layout
	  user_signed_in? ? 'dashboard' : 'application'
  end

  def role
  	current_user.role
  end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
	
	# Update buyers balance
	# Update sellers balance
	def update
		# NOTE: Performance Heavy, use indexes as alternative
		@code = Code.where(code: params[:codes][:code]).first 

		if @code.present?
			if current_user.balance.update_attribute(:amount_cents, current_user.balance.amount_cents += @code.value_cents)
				@code.destroy
				flash[:success] = "Gift card code accepted"
				redirect_to dashboard_path
			end
		else
			flash[:danger] = "Code is invalid"
			redirect_to dashboard_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :allow_home

  def home
  end

  def features
  end

  private
	  def allow_home
	  	if user_signed_in? && role == "delivery"
	  		redirect_to dashboard_path
	  	end
	  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 12).order("created_at DESC")
  end

  def show
    @product = Product.friendly.find(params[:id])
  end

  private	
  	def product_params
  		params.require(:product).permit(:name, :price_cents, :quantity, :description, :product_image, :shop_id)
  	end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  def index
  	@sellers = User.order("created_at DESC").limit(20)
  end

  def show
  	@seller = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def role
	  current_user.role
	end
end

app/helpers/clear_helper.rb
module ClearHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/application/_footer.html.erb
<footer>
	<div class="container">
		<div class="row footer-nav">
			<div class="col-md-4">
				<h4>Get Involved</h4>
				<ul>
					<li><a href="#">Register</a></li>
					<li><a href="#">Sign In</a></li>
					<li><a href="#">Feedback</a></li>
				</ul>
			</div>
			<div class="col-md-4">
				<h4>Business</h4>
				<ul>
					<li><a href="#">Gift cards</a></li>
					<li><a href="#">Features</a></li>
					<li><a href="#">Advertisments</a></li>
				</ul>
			</div>
			<div class="col-md-4">
				<h4>About Us</h4>
				<ul>
					<li><a href="#">About</a></li>
					<li><a href="#">How it all works?</a></li>
					<li><a href="#">Our Rules</a></li>
				</ul>
			</div>
		</div>
		<p class="pull-left gray">&copy; Belize Enterprises 2016</p>
		<p class="pull-right gray">From us to you with &#9829;</p>
	</div>
</footer>

app/views/application/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Belize Enterprises", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Sellers", sellers_path %></li>
        <li><%= link_to "Features", features_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
           <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Sign In", new_user_session_path, class: "sign-in" %></li>
            <li><%= link_to "Register", new_user_registration_path, class: "register" %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/application/_menu.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
	<ul class="sidebar-nav">
		<li class="sidebar-brand">
			<% if role == "normal" %>
				<%= link_to "Belize Enterprises", root_path %>
			<% else %>
				<%= link_to "BPMS Delivery", dashboard_path %>
			<% end %>
		</li>
		<li>
			<%= link_to "Dashboard", dashboard_path %>
		</li>
		<% if role == "normal" %>
			<li>
				<%= link_to "Products", dashboard_products_path %>
			</li>
			<li>
				<%= link_to "Purchases", dashboard_purchases_path %>
			</li>
		<% elsif role == "delivery" %>
			<li><%= link_to "Orders", dashboard_orders_path %></li>
			<li><%= link_to "Staff", dashboard_staff_path %></li>
		<% end %>
		<li>
			<%= link_to "Account", dashboard_account_path %>
		</li>
		<li>
			<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		</li>
	</ul>
</div>
	<!-- /#sidebar-wrapper -->

app/views/application/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>